// Peptide South Africa — Peptide Research MCP server.
//
// Hand-written replacement for the file that used to be auto-generated by the
// @lovable.dev/mcp-js Vite plugin (bundled from src/lib/mcp/index.ts). That
// plugin and package are gone, so this is now a plain, self-contained Deno
// edge function built directly on the official MCP TypeScript SDK
// (npm:@modelcontextprotocol/sdk), exposing the same 4 tools with the same
// names, descriptions, input schemas and output shapes as before:
//   - list_peptides
//   - get_peptide
//   - check_stack_compatibility
//   - recommend_peptides_for_goal
//
// This is a public, read-only research catalogue with no user data and no
// sessions, so it's served over the Streamable HTTP transport in stateless
// mode (a fresh McpServer + transport per request, JSON responses instead of
// SSE streaming). verify_jwt = false for this function in supabase/config.toml
// — intentionally public, matching the previous behaviour.
//
// Data: the 4 tools read from a static peptide/goal/stacking catalogue that
// lives in src/data/*.ts in the main app. Deno edge functions can't import
// from src/ (Supabase's function bundler only resolves relative imports
// within supabase/functions/ and remote/npm specifiers), and there's no
// build step left to inline it automatically. The old generated bundle
// solved this by having the Vite plugin literally inline the resolved
// contents of those src/data modules into the bundle at build time. We
// follow the same approach by hand: ./data.ts is a static snapshot of that
// same merged data (see the comment at the top of that file for how to
// regenerate it). There's no Supabase table backing this catalogue, so
// querying Postgres instead would add a dependency for no real benefit.
import { McpServer } from "npm:@modelcontextprotocol/sdk@1.30.0/server/mcp.js";
import { WebStandardStreamableHTTPServerTransport } from "npm:@modelcontextprotocol/sdk@1.30.0/server/webStandardStreamableHttp.js";
import { z } from "npm:zod@3";
import {
  peptides,
  categoryConfig,
  goalToCategories,
  goalLabels,
  stackingInteractions,
  type PeptideCategory,
} from "./data.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, mcp-session-id, mcp-protocol-version, last-event-id",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Expose-Headers": "mcp-session-id, mcp-protocol-version",
};

const categoryValues = Object.keys(categoryConfig) as [PeptideCategory, ...PeptideCategory[]];
const goalIds = Object.keys(goalToCategories) as [string, ...string[]];

// Builds a fresh MCP server (with all 4 tools registered) for each request.
// A new instance per request is the recommended pattern for stateless
// Streamable HTTP servers so requests never share in-memory state.
function createServer(): McpServer {
  const server = new McpServer({
    name: "peptide-south-africa-mcp",
    title: "Peptide South Africa — Peptide Research",
    version: "0.1.0",
  });

  server.registerTool(
    "list_peptides",
    {
      title: "List peptides",
      description:
        "Browse the Peptide South Africa peptide research catalog. Optionally filter by category or search term (matches name, short name, or mechanism).",
      inputSchema: {
        category: z
          .enum(categoryValues)
          .optional()
          .describe("Filter by peptide category (e.g. 'weight-loss', 'healing', 'cognitive')."),
        search: z.string().trim().min(1).optional().describe("Free-text search across name, short name and mechanism."),
        limit: z.number().int().min(1).max(100).optional().describe("Max results to return (default 25)."),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    ({ category, search, limit }) => {
      const q = search?.toLowerCase();
      const filtered = peptides.filter((p) => {
        if (category && p.category !== category) return false;
        if (q) {
          const hay = `${p.name} ${p.shortName} ${p.mechanism}`.toLowerCase();
          if (!hay.includes(q)) return false;
        }
        return true;
      });
      const capped = filtered.slice(0, limit ?? 25);
      const rows = capped.map((p) => ({
        id: p.id,
        name: p.name,
        shortName: p.shortName,
        category: p.category,
        halfLife: p.halfLife,
        longevityScore: p.longevityScore,
        mechanism: p.mechanism,
      }));
      return {
        content: [
          {
            type: "text" as const,
            text: `Found ${filtered.length} peptides${
              filtered.length > capped.length ? ` (showing first ${capped.length})` : ""
            }.\n\n${rows.map((r) => `• ${r.name} (${r.id}) — ${r.category}`).join("\n")}`,
          },
        ],
        structuredContent: { total: filtered.length, returned: capped.length, peptides: rows },
      };
    },
  );

  server.registerTool(
    "get_peptide",
    {
      title: "Get peptide details",
      description:
        "Return the full research profile for a single peptide: mechanism, benefits, dosing by experience level, expected results, risks and references.",
      inputSchema: {
        id: z
          .string()
          .trim()
          .min(1)
          .describe("Peptide id (e.g. 'bpc157', 'ipamorelin', 'retatrutide'). Use list_peptides to discover ids."),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    ({ id }) => {
      const needle = id.toLowerCase().replace(/[-_\s]/g, "");
      const peptide = peptides.find(
        (p) =>
          p.id.toLowerCase() === id.toLowerCase() ||
          p.id.toLowerCase().replace(/[-_\s]/g, "") === needle ||
          p.shortName.toLowerCase() === id.toLowerCase() ||
          p.name.toLowerCase() === id.toLowerCase(),
      );
      if (!peptide) {
        return {
          content: [{ type: "text" as const, text: `No peptide found for id "${id}". Try list_peptides to browse.` }],
          isError: true,
        };
      }
      const summary = [
        `${peptide.name} (${peptide.shortName}) — ${peptide.category}`,
        peptide.halfLife ? `Half-life: ${peptide.halfLife}` : null,
        `Mechanism: ${peptide.mechanism}`,
        `Administration: ${peptide.administration}`,
        `Frequency: ${peptide.frequency}`,
        "",
        "Dosing:",
        `  Beginner: ${peptide.dosing.beginner}`,
        `  Intermediate: ${peptide.dosing.intermediate}`,
        `  Advanced: ${peptide.dosing.advanced}`,
        `  Athlete: ${peptide.dosing.athlete}`,
        "",
        `Benefits: ${peptide.benefits.join("; ")}`,
        `Risks: ${peptide.risks.join("; ")}`,
        "",
        "Research use only. Not FDA approved for human consumption.",
      ]
        .filter(Boolean)
        .join("\n");
      return {
        content: [{ type: "text" as const, text: summary }],
        structuredContent: { peptide },
      };
    },
  );

  server.registerTool(
    "check_stack_compatibility",
    {
      title: "Check peptide stack compatibility",
      description:
        "Check the compatibility (synergistic, compatible, caution, avoid) between two peptides using the Peptide South Africa stacking matrix.",
      inputSchema: {
        peptideId1: z.string().trim().min(1).describe("First peptide id (e.g. 'bpc157')."),
        peptideId2: z.string().trim().min(1).describe("Second peptide id (e.g. 'tb500')."),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    ({ peptideId1, peptideId2 }) => {
      const a = peptideId1.toLowerCase();
      const b = peptideId2.toLowerCase();
      const match = stackingInteractions.find(
        (i) =>
          (i.peptideId1.toLowerCase() === a && i.peptideId2.toLowerCase() === b) ||
          (i.peptideId1.toLowerCase() === b && i.peptideId2.toLowerCase() === a),
      );
      if (!match) {
        return {
          content: [
            {
              type: "text" as const,
              text: `No documented interaction between ${peptideId1} and ${peptideId2}. Absence of data is not a safety guarantee — consult a qualified clinician.`,
            },
          ],
          structuredContent: { found: false },
        };
      }
      return {
        content: [
          {
            type: "text" as const,
            text: `${peptideId1} + ${peptideId2}: ${match.compatibility.toUpperCase()}\n\n${match.notes}${
              match.timing ? `\n\nTiming: ${match.timing}` : ""
            }`,
          },
        ],
        structuredContent: { found: true, interaction: match },
      };
    },
  );

  server.registerTool(
    "recommend_peptides_for_goal",
    {
      title: "Recommend peptides for a goal",
      description:
        "Return peptides from the Peptide South Africa catalog that map to a user goal (fat-loss, muscle-gain, recovery, longevity, cognitive, energy, sleep, metabolic), sorted by longevity score.",
      inputSchema: {
        goal: z.enum(goalIds).describe("User goal id."),
        limit: z.number().int().min(1).max(20).optional().describe("Max results (default 8)."),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    ({ goal, limit }) => {
      const cats = new Set(goalToCategories[goal] ?? []);
      const matches = peptides
        .filter((p) => cats.has(p.category))
        .sort((a, b) => (b.longevityScore ?? 0) - (a.longevityScore ?? 0))
        .slice(0, limit ?? 8)
        .map((p) => ({
          id: p.id,
          name: p.name,
          category: p.category,
          longevityScore: p.longevityScore,
          mechanism: p.mechanism,
          dosingBeginner: p.dosing.beginner,
        }));
      return {
        content: [
          {
            type: "text" as const,
            text: `Top peptides for goal "${goalLabels[goal] ?? goal}":\n\n${matches
              .map((m) => `• ${m.name} (${m.id}) — score ${m.longevityScore}`)
              .join("\n")}\n\nResearch use only. Not medical advice.`,
          },
        ],
        structuredContent: { goal, peptides: matches },
      };
    },
  );

  return server;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  if (req.method !== "POST") {
    // Stateless mode: there's no session to open an SSE stream against (GET)
    // or tear down (DELETE), so only POST request/response is supported.
    return new Response(
      JSON.stringify({
        jsonrpc: "2.0",
        error: { code: -32000, message: "Method not allowed. This MCP endpoint only supports POST." },
        id: null,
      }),
      { status: 405, headers: { ...corsHeaders, "Content-Type": "application/json", Allow: "POST, OPTIONS" } },
    );
  }

  try {
    const server = createServer();
    const transport = new WebStandardStreamableHTTPServerTransport({
      // Stateless: no session id is generated or required.
      sessionIdGenerator: undefined,
      // Simple synchronous, read-only tools — plain JSON responses are all
      // that's needed, no SSE streaming.
      enableJsonResponse: true,
    });
    await server.connect(transport);

    const response = await transport.handleRequest(req);

    const headers = new Headers(response.headers);
    for (const [key, value] of Object.entries(corsHeaders)) {
      headers.set(key, value);
    }
    return new Response(response.body, { status: response.status, headers });
  } catch (error) {
    console.error("Error handling MCP request:", error);
    return new Response(
      JSON.stringify({
        jsonrpc: "2.0",
        error: { code: -32603, message: "Internal server error" },
        id: null,
      }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});
